"""Автоматическая генерация конфигурации для любой GPU + модели."""

from __future__ import annotations

import os
import shutil
import subprocess
from dataclasses import dataclass
from pathlib import Path

from gpu_profiles import (
    GPUSpec,
    ModelSpec,
    OVERHEAD_MB,
    detect_gpu,
    calculate_max_context,
    get_context_tiers,
)


@dataclass
class HardwareProfile:
    gpu: GPUSpec
    cpu_cores: int
    ram_mb: int
    disk_free_gb: float
    driver_version: str
    llama_server_path: str | None


@dataclass
class DeploymentConfig:
    model: ModelSpec
    model_path: str
    n_gpu_layers: int
    ctx_size: int
    cache_type_k: str
    cache_type_v: str
    flash_attn: str
    threads: int
    parallel: int
    reasoning: str
    vram_headroom_mb: int
    context_tiers: dict[str, list[int]]


# =====================================================================
# Hardware Detection
# =====================================================================

def detect_hardware() -> HardwareProfile:
    """Полное определение железа."""
    gpu = detect_gpu()

    cpu_cores = os.cpu_count() or 4

    # RAM
    ram_mb = 0
    try:
        with open("/proc/meminfo") as f:
            for line in f:
                if line.startswith("MemTotal:"):
                    ram_mb = int(line.split()[1]) // 1024
                    break
    except OSError:
        pass

    # Disk
    disk_free_gb = 0.0
    try:
        usage = shutil.disk_usage("/")
        disk_free_gb = usage.free / (1024 ** 3)
    except OSError:
        pass

    # Driver version
    driver = ""
    try:
        result = subprocess.run(
            ["nvidia-smi", "--query-gpu=driver_version", "--format=csv,noheader"],
            capture_output=True, text=True, timeout=5,
        )
        driver = result.stdout.strip().split("\n")[0]
    except Exception:
        pass

    # llama-server
    llama_path = shutil.which("llama-server")

    return HardwareProfile(
        gpu=gpu,
        cpu_cores=cpu_cores,
        ram_mb=ram_mb,
        disk_free_gb=disk_free_gb,
        driver_version=driver,
        llama_server_path=llama_path,
    )


# =====================================================================
# Deployment Configuration
# =====================================================================

def generate_deployment(
    hw: HardwareProfile,
    model: ModelSpec,
    model_path: str,
    kv_type: str = "auto",
) -> DeploymentConfig:
    """Рассчитать оптимальные параметры llama-server."""
    gpu = hw.gpu
    available_mb = gpu.vram_mb - model.vram_mb - OVERHEAD_MB

    # KV cache type
    if kv_type == "auto":
        if available_mb < 1500:
            kv_type = "q4_0"
        else:
            kv_type = "q8_0"

    # Context size
    ctx_size = calculate_max_context(gpu, model, kv_type)
    ctx_size = min(ctx_size, 65536)  # практический потолок

    # GPU layers: 99 = all (если модель влезает)
    if model.vram_mb + OVERHEAD_MB < gpu.vram_mb:
        n_gpu_layers = 99
    else:
        # Частичная загрузка: пропорция от layers
        ratio = (gpu.vram_mb - OVERHEAD_MB) / model.vram_mb
        n_gpu_layers = max(1, int(model.num_layers * min(ratio, 1.0)))

    # Flash attention
    flash_attn = "on" if gpu.supports_flash else "off"

    # Threads: физические ядра - 2 (оставить OS)
    threads = max(1, hw.cpu_cores - 2)

    # Parallel: 1 для consumer, 2 если много headroom
    parallel = 1
    if available_mb > 8000:
        parallel = 2

    # Reasoning
    reasoning = "off"
    if model.supports_thinking:
        reasoning = "off"  # дефолт без thinking (быстрее)

    # Headroom
    from gpu_profiles import kv_bytes_per_token
    kv_at_max = int(ctx_size * kv_bytes_per_token(model, kv_type) / (1024 * 1024))
    headroom = gpu.vram_mb - model.vram_mb - OVERHEAD_MB - kv_at_max

    # Тиры контекста для бенчмарков
    tiers = get_context_tiers(gpu, model, kv_type)

    return DeploymentConfig(
        model=model,
        model_path=model_path,
        n_gpu_layers=n_gpu_layers,
        ctx_size=ctx_size,
        cache_type_k=kv_type,
        cache_type_v=kv_type,
        flash_attn=flash_attn,
        threads=threads,
        parallel=parallel,
        reasoning=reasoning,
        vram_headroom_mb=max(0, headroom),
        context_tiers=tiers,
    )


# =====================================================================
# Generators
# =====================================================================

def generate_env_file(config: DeploymentConfig) -> str:
    """Сгенерировать содержимое /etc/default/llama-server."""
    return f"""# Generated by qvant auto_config
# Model: {config.model.display_name} ({config.model.quant})
LLAMA_MODEL_PATH={config.model_path}
LLAMA_PORT=11434
LLAMA_GPU_LAYERS={config.n_gpu_layers}
LLAMA_CTX_SIZE={config.ctx_size}
LLAMA_FLASH_ATTN={config.flash_attn}
LLAMA_CACHE_TYPE_K={config.cache_type_k}
LLAMA_CACHE_TYPE_V={config.cache_type_v}
LLAMA_THREADS={config.threads}
LLAMA_PARALLEL={config.parallel}
LLAMA_REASONING={config.reasoning}
"""


def generate_systemd_service() -> str:
    """Сгенерировать llama-server.service с EnvironmentFile."""
    return """[Unit]
Description=llama.cpp Server (qvant managed)
After=network-online.target
Wants=network-online.target
Conflicts=ollama.service

[Service]
Type=simple
User=root
EnvironmentFile=/etc/default/llama-server
ExecStart=/usr/local/bin/llama-server \
  --model ${LLAMA_MODEL_PATH} \
  --host 127.0.0.1 \
  --port ${LLAMA_PORT} \
  --n-gpu-layers ${LLAMA_GPU_LAYERS} \
  --ctx-size ${LLAMA_CTX_SIZE} \
  --flash-attn ${LLAMA_FLASH_ATTN} \
  --cache-type-k ${LLAMA_CACHE_TYPE_K} \
  --cache-type-v ${LLAMA_CACHE_TYPE_V} \
  --threads ${LLAMA_THREADS} \
  --parallel ${LLAMA_PARALLEL} \
  --reasoning ${LLAMA_REASONING}
Restart=on-failure
RestartSec=5
LimitNOFILE=65536
KillSignal=SIGTERM
TimeoutStopSec=30

[Install]
WantedBy=multi-user.target
"""


def save_generated_files(config: DeploymentConfig, output_dir: Path) -> dict[str, Path]:
    """Сохранить все сгенерированные файлы."""
    output_dir.mkdir(parents=True, exist_ok=True)

    files = {}

    # Environment file
    env_path = output_dir / "llama-server.env"
    env_path.write_text(generate_env_file(config))
    files["env"] = env_path

    # Systemd service
    svc_path = output_dir / "llama-server.service"
    svc_path.write_text(generate_systemd_service())
    files["service"] = svc_path

    return files


def save_hardware_profile(hw: HardwareProfile, path: Path) -> None:
    """Сохранить hardware_profile.json."""
    import json
    data = {
        "gpu": {
            "name": hw.gpu.name,
            "vram_mb": hw.gpu.vram_mb,
            "compute_cap": hw.gpu.compute_cap,
            "bandwidth_gbps": hw.gpu.bandwidth_gbps,
            "supports_flash": hw.gpu.supports_flash,
        },
        "cpu_cores": hw.cpu_cores,
        "ram_mb": hw.ram_mb,
        "disk_free_gb": round(hw.disk_free_gb, 1),
        "driver_version": hw.driver_version,
        "llama_server_path": hw.llama_server_path,
    }
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2, ensure_ascii=False))
